name: Tom Charman
favicon: null
layout_spectrum: 0.14150104904547334
typography_spectrum: 0.2544928202405572
title: Tom Charman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.423032179242
  lightness: 0.10996339260600507
  saturation: 0.6020401590503752
  rhythmicContrast: 0.7307258159853518
purpose: []
