name: Tom Charman
favicon: null
layout_spectrum: 0.49907
typography_spectrum: 0.06722
title: Tom Charman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141013'
    - '#fefefe'
    - '#565255'
    - '#9a9699'
    - '#61d0f0'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
