name: Tom Charman
favicon: null
layout_spectrum: 0.50757
typography_spectrum: 0.07232
title: Tom Charman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6875
  lightness: 0.10996339260600507
  saturation: 0.5625
  rhythmicContrast: 0.7307258159853518
purpose: []
